name: C/C++ CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  euler:
    name: To creating nothing${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
